# Welcome to Jekyll!
#
remote_theme: "mmistakes/minimal-mistakes@4.19.0"

minimal_mistakes_skin    : "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

title                    : "Integration Trench"
subtitle                 : "Sharing lessons from practical experience" # site tagline that appears below site title in masthead
description: "This blog shares my mistakes and lessons in identity integration and software in general."

# Site Author
author:
  name             : "Craig Martin"
  #avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Learning and sharing"
  location         : "Pacific Northwest"
  email            :
  links:    
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url:    "https://twitter.com/getcmart"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/craig-martin"
      
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url:    "https://twitter.com/getcmart"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/craig-martin"
